# Generated by Django 5.2.17 on 2026-08-18 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_relatado', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('diagnostico', 'Em diagnóstico'), ('orcamento', 'Orçamento enviado'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('manutencao', 'Em manutenção'), ('conferencia', 'Em conferência'), ('pronto', 'Pronto para retirada'), ('entregue', 'Entregue')], default='aberta', max_length=30)),
                ('aprovado_cliente', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='veiculos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico_responsavel', models.CharField(max_length=100)),
                ('problema_encontrado', models.TextField()),
                ('data_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='veiculos.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito')], max_length=20)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='veiculos.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('andamento', 'Em andamento'), ('concluido', 'Concluído')], default='aguardando', max_length=20)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='veiculos.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='veiculos.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='veiculos.veiculo'),
        ),
    ]
